-- schema_target (целевая схема по проектированию)
--
-- Эти файлы предназначены для курсовой/пояснительной записки:
-- здесь схема представлена в виде "чистых" SQL-скриптов:
-- - CREATE TYPE (ENUM)
-- - CREATE TABLE
-- - CONSTRAINTS (PK/UK/FK/CHECK)
-- - DEFAULT
-- - INDEXES
--
-- Важно: в таблице transactions поле currency_code НЕ связано внешним ключом
-- с crypto_currencies(symbol), т.к. в проекте оно может хранить составные
-- значения (например "USD->RUB"), что невозможно при FK.
